# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: ~
        name: 'GESTION_DECHETS_SESSION'
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 3600
        storage_factory_id: session.storage.factory.native

    # Enable the Form component
    form:
        enabled: true
        csrf_protection: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
