security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _username
                password_parameter: _password
                default_target_path: app_login
                always_use_default_target_path: false
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                domain: ~
            stateless: false
            entry_point: App\Security\LoginFormAuthenticator
            custom_authenticators:
                - App\Security\LoginFormAuthenticator

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/signalement, roles: PUBLIC_ACCESS }
        - { path: ^/admin/dashboard, roles: ROLE_ADMIN }
        - { path: ^/agent/dashboard, roles: ROLE_AGENT }
        - { path: ^/citoyen/dashboard, roles: ROLE_CITOYEN }
        - { path: ^/admin/export/, roles: ROLE_ADMIN }
        - { path: ^/agent/export/, roles: ROLE_AGENT }
        - { path: ^/citoyen/export/, roles: ROLE_CITOYEN }
        - { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

when@prod:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 12
                time_cost: 4
                memory_cost: 14
